services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        restart: unless-stopped
        volumes:
            - ./tmp/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
    mysql:
        container_name: mysql
        command: mysqld --character-set-filesystem=utf8mb4 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password --max_allowed_packet=256M --tls-version=''
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 1G
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE_TABLE_NAME}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=dxpcloud
        healthcheck:
             interval: 5s
             retries: 50
             start_period: 30s
             test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
             timeout: 5s
        image: mysql:8.0
        ports:
            - 127.0.0.1:13306:3306
        volumes:
            - ./database_import:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
        networks:
            - liferay-net
    liferay:
        container_name: ${ID_NAME}
        build: 
            context: ./build/liferay
            args:
                LIFERAY_VERSION: ${LIFERAY_VERSION}
        image: ${IMAGE_NAME}
        deploy:
            resources:
                limits:
                    memory: 6G
                reservations:
                    memory: 6G
        depends_on:
            mysql:
                condition: service_healthy   
        environment:
            - LCP_LIFERAY_UPGRADE_ENABLED=${LCP_LIFERAY_UPGRADE_ENABLED:-}
            - LCP_SECRET_DATABASE_HOST=mysql
            - LCP_SECRET_DATABASE_PASSWORD=password
            - LCP_SECRET_DATABASE_USER=root
            - LCP_PROJECT_ENVIRONMENT=spinner_modl
            - LIFERAY_DISABLE_TRIAL_LICENSE=true
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=org.mariadb.jdbc.Driver
            -                                                                    LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://mysql/${MYSQL_DATABASE_TABLE_NAME}?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&passwordCharacterEncoding=UTF-8&permitMysqlScheme&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=${MYSQL_USERNAME}
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=${MYSQL_PASSWORD}
            - LIFERAY_JPDA_ENABLED=true
            - LIFERAY_UPGRADE_ENABLED=false
            - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
            - LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS=*
            - LIFERAY_WORKSPACE_ENVIRONMENT=${LIFERAY_WORKSPACE_ENVIRONMENT}
            - LOCAL_STACK=true
            - MODL_CUSTOMER_USERS_PASSWORD=liferaydevsecops
            - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS_PERIOD_VERIFY=false
        extra_hosts:
            - host.docker.internal:host-gateway
        hostname: liferay-docker
        ports:
            - ${PORT}:8080
        volumes:
            - liferay_document_library-docker:/opt/liferay/data
            - ./scripts:/mnt/liferay/scripts
            - ./deploy:/opt/liferay/deploy
            - ./liferay_mount/files/portal_properties:/mnt/liferay/files
        networks:
            - liferay-net
volumes:
    liferay_document_library-docker:
    mysql_data:
networks:
  liferay-net:
    external: true
