services:
  liferay_container:
    container_name: akarmi4
    build: 
      context: ./build/liferay
      args:
        LIFERAY_VERSION: liferay/dxp:2024.q1.8
    image: liferay/dxp2024.q1.8
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
    depends_on:
      mysql:
        condition: service_healthy   
    environment:
            - LCP_LIFERAY_UPGRADE_ENABLED=${LCP_LIFERAY_UPGRADE_ENABLED:-}
            - LCP_SECRET_DATABASE_HOST=mysql
            - LCP_SECRET_DATABASE_PASSWORD=password
            - LCP_SECRET_DATABASE_USER=root
            - LCP_PROJECT_ENVIRONMENT=spinner_modl
            - LIFERAY_DISABLE_TRIAL_LICENSE=false
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=org.mariadb.jdbc.Driver
            -                                                                    LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://mysql/liferay_primary_db?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&passwordCharacterEncoding=UTF-8&permitMysqlScheme&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=password
            - LIFERAY_JPDA_ENABLED=true
            - LIFERAY_UPGRADE_ENABLED=false
            - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
            - LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS=*
            - LIFERAY_WORKSPACE_ENVIRONMENT=workspace_env
            - LOCAL_STACK=true
            - MODL_CUSTOMER_USERS_PASSWORD=liferaydevsecops
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: hostname
    ports:
      - 127.0.0.1:48080:8080
    volumes:
      - liferay_volume:/opt/liferay/data
    networks:
      - env-tiger_liferay-net
volumes:
  liferay_volume:
networks:
  env-tiger_liferay-net:
    external: true